version: "3.8"
services: 
    
    marketplace:
        build:
            context: .
            dockerfile: marketplace/Dockerfile
        environment: 
            RECOMMENDATIONS_HOST: recommendations
            INVENTORY_HOST: inventory
        image: marketplace
        networks: 
            - microservices
        ports:
            - 5000:5000

    recommendations:
        build:
            context: .
            dockerfile: recommendations/Dockerfile
        image: recommendations
        networks:
            - microservices

            inventory:
        build:
            context: .
            dockerfile: inventory/Dockerfile
        image: inventory
        networks:
            - microservices

networks:
    microservices:
