"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Book(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text = ...

    def __init__(self,
        *,
        name : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"name",b"name"]) -> None: ...
global___Book = Book

class BookList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    BOOKS_FIELD_NUMBER: builtins.int

    @property
    def books(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Book]: ...

    def __init__(self,
        *,
        books : typing.Optional[typing.Iterable[global___Book]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"books",b"books"]) -> None: ...
global___BookList = BookList
