apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  labels: 
    app: inventory
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: keyem4251/inventory:0.1
